version: "2.3"

services:
  vision-srv:
    entrypoint: entrypoint.sh
    runtime: nvidia
    network_mode: host
    volumes:
      - visionvolume:/home/data
    devices:
      - /dev/video0
      - /dev/video1
    build:
      context: .
    restart: always

volumes:
    visionvolume:
        external: false
