version: "2.3"

services:
  vision-srv:
    runtime: nvidia
    network_mode: host
    volumes:
      - visionvolume:/home/data
    devices:
      - /dev/back
    build:
      context: .
    env_file: ./.env
    restart: always
    command: sh -c "python3 robot_vision.py v4l2:///dev/back --apriltag -e env.json -c camera-back.json --width 1280 --height 720"

  # roboflow-srv:
  #   image: roboflow/roboflow-inference-server-jetson-5.1.1:latest
  #   privileged: true
  #   runtime: nvidia
  #   network_mode: host
  #   ports:
  #     - "9001:9001"
  #   env_file: ./.env
  #   volumes:
  #     - inference-cache:/tmp/cache
  #   restart: always

volumes:
  visionvolume:
      external: false
  # inference-cache:
  #   external: false
