version: "3.8"

services:
  vision-srv:
    entrypoint: record-clips.py
    runtime: nvidia
    network: host
    volumes:
      - visionvolume:/home/data
    devices:
      - /dev/video0
      - /dev/video1
    build:
      context: .
    deploy:
      restart_policy:
        condition: any
        delay: 0s
        window: 10sg

volumes:
    visionvolume:
        external: false